/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kodan (https://sketchfab.com/kodya)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dirty-braun-fs80-28f8143de5ce4a2fb5841421fb43cf31
title: Dirty Braun FS80
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/dirty_braun_fs80.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.02, 0, -0.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.64}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[403.19, -0.57, -0.26]}
            rotation={[-Math.PI / 2, 0, 2.09]}
          >
            <group position={[0, 9.35, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_leg_bot_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
          <group
            position={[403.21, 32.69, 2.8]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_screen_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[404.4, 11.19, -0.26]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_mid_leg_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group
            position={[395.3, 36.71, 6.58]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_circle_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group
            position={[403.19, 25.08, 3.37]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_main_bot_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group
            position={[403.19, 25.08, 3.37]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_main_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group
            position={[403.2, 32.67, -9.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_back_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group position={[403.28, 19.68, -9.47]} rotation={[Math.PI, 0, 0]}>
            <group position={[-0.71, -0.3, -0.11]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_6_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
          <group
            position={[401.66, 19.76, -9.38]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[1.53, -11.04, 12.93]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_big_aux_Material_#47_0"].geometry}
                material={materials.Material_47}
              />
            </group>
          </group>
          <group
            position={[407.42, 32.69, -10.88]}
            rotation={[-Math.PI / 2, -0.61, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_bolt_circle_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group position={[401.36, 19.47, 6.83]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_1_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[408.95, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_5_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group
            position={[404.73, 19.69, -9.57]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-1.53, -11.19, 12.76]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_back_Material_#47_0"].geometry}
                material={materials.Material_47}
              />
            </group>
          </group>
          <group
            position={[407.42, 32.69, -10.88]}
            rotation={[-Math.PI / 2, -0.61, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_bolt_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group
            position={[411.82, 21.06, 6.67]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_glass_Material_#50_0"].geometry}
              material={materials.Material_50}
            />
          </group>
          <group
            position={[409.95, 20.63, 6.53]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_p1_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group
            position={[403.19, 25.08, 3.37]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_main_bot_back_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group
            position={[412.57, 20.63, 6.53]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_p2_Material_#47_0"].geometry}
              material={materials.Material_47}
            />
          </group>
          <group position={[403.16, 19.47, 6.83]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_2_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[404.83, 19.47, 6.83]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_6_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[406.64, 19.47, 6.83]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_7_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[409.92, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_6_Material_#46_0_1"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[410.84, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_7_Material_#46_0_1"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[411.82, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_8_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[412.81, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_9_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[413.74, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_10_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[414.72, 19.47, 6.78]} rotation={[0, 0, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["lp_k_11_Material_#46_0"].geometry}
              material={materials.Material_46}
            />
          </group>
          <group position={[403.99, 19.68, -9.47]} rotation={[Math.PI, 0, 0]}>
            <group position={[-0.71, -0.3, -0.11]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_007_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
          <group position={[404.7, 19.68, -9.47]} rotation={[Math.PI, 0, 0]}>
            <group position={[-0.71, -0.3, -0.11]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_008_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
          <group position={[403.99, 20.24, -9.47]} rotation={[Math.PI, 0, 0]}>
            <group position={[-0.71, -0.3, -0.11]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_009_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
          <group position={[404.7, 20.24, -9.47]} rotation={[Math.PI, 0, 0]}>
            <group position={[-0.71, -0.3, -0.11]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_010_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
          <group position={[403.28, 20.24, -9.47]} rotation={[Math.PI, 0, 0]}>
            <group position={[-0.71, -0.3, -0.11]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["lp_aux_011_Material_#46_0"].geometry}
                material={materials.Material_46}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dirty_braun_fs80.glb");
